apply plugin: 'com.android.application'

def getVersionName = { return versionName }
def getVersionCode = { return versionCode }
def getApplicationId = { return applicationId }

android {
    compileSdk 37
    defaultConfig {
        applicationId getApplicationId()
        minSdkVersion 26
        targetSdk 35
        versionCode getVersionCode()
        versionName getVersionName()
        multiDexEnabled true
    }
    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    namespace 'com.layoutxml.twelveish'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.4'
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    // implementation 'com.google.android.support:wearable:2.9.0'
    implementation 'com.google.android.gms:play-services-wearable:20.0.1'

    // Modern Wear OS Watch Face libraries
    implementation "androidx.wear.watchface:watchface:1.2.1"
    implementation "androidx.wear.watchface:watchface-complications-rendering:1.2.1"
    implementation "androidx.wear.watchface:watchface-editor:1.2.1"
    implementation "androidx.wear.watchface:watchface-style:1.2.1"
    implementation "androidx.wear.watchface:watchface-guava:1.2.1"
    implementation "androidx.wear.watchface:watchface-editor-guava:1.2.1"

    implementation 'androidx.percentlayout:percentlayout:1.0.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'androidx.wear:wear:1.4.0'
    compileOnly 'com.google.android.wearable:wearable:2.9.0'
    implementation "androidx.constraintlayout:constraintlayout:2.2.2"
    annotationProcessor 'org.projectlombok:lombok:1.18.46'
    //noinspection AnnotationProcessorOnCompilePath
    compileOnly 'org.projectlombok:lombok:1.18.46'
}
