plugins {
    id 'com.android.application'
}

android {
    namespace 'com.psychowood.twelveish.wff'
    compileSdk 37

    defaultConfig {
        applicationId "com.psychowood.twelveish.wff"
        minSdkVersion 33
        targetSdk 35
        versionCode 500
        versionName "1.0"
    }

    buildTypes {
        debug {
            minifyEnabled true
        }

        release {
            minifyEnabled false
            shrinkResources false
        }
    }

    buildFeatures {
        buildConfig false
        resValues false
    }
}

dependencies {
}
