plugins {
    id 'com.android.application'
}

android {
    namespace 'com.psychowood.twelveishredux'
    compileSdk 37

    defaultConfig {
        applicationId "com.psychowood.twelveishredux"
        minSdkVersion 33
        targetSdk 35
        versionCode 501
        versionName "2.5.0"
    }

    buildTypes {
        release {
            minifyEnabled true
        }

        debug {
            minifyEnabled false
            shrinkResources false
        }
    }

    buildFeatures {
        buildConfig false
        resValues false
    }
}

dependencies {
}
