plugins {
    id 'com.android.application'
}

android {
    namespace 'com.psychowood.twelveish.wff'
    compileSdk 37

    defaultConfig {
        applicationId "com.psychowood.twelveish.wff"
        minSdkVersion 33
        targetSdk 35
        versionCode 500
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    // Watch Face Format modules don't typically have code dependencies
}
