/*
 * Copyright (c) 2018. LayoutXML
 * Created by LayoutXML.
 *
 */

apply plugin: 'com.android.application'

def getVersionName = { return versionName }
def getVersionCode = { return versionCode }
def getApplicationId = { return applicationId }

android {
    compileSdk 37

    defaultConfig {
        applicationId getApplicationId()
        minSdkVersion 26
        targetSdk 34
        versionCode getVersionCode()
        versionName getVersionName()

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    namespace 'com.layoutxml.twelveish'

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.2'
    implementation 'com.google.code.gson:gson:2.14.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test:runner:1.7.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    wearApp project(':app')
    implementation 'com.google.android.gms:play-services-wearable:20.0.1'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'com.google.dagger:dagger:2.60.1'
    annotationProcessor 'com.google.dagger:dagger-compiler:2.60.1'
}